services:
  todoapi:
    image: todoapi
    build:
      context: .
      dockerfile: ToDoApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  

  todo_database:
    image: postgres:latest
    container_name: todo_database
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/todo-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"