name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Validate branch naming convention
      if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'feature/')
      run: |
        echo "Branch name for pull requests must start with 'feature/'."
        exit 1

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ToDoApi.sln

    - name: Build
      run: dotnet build ToDoApi.sln --no-restore

    - name: Test
      run: dotnet test ToDoApi.sln --no-build --verbosity normal
