name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check branch naming convention
      if: startsWith(github.ref_name, 'feature/')
      run: echo "Branch name is valid"
    - name: Fail if branch name is invalid
      if: "!startsWith(github.ref_name, 'feature/')"
      run: |
        echo "Branch name must start with 'feature/'."
        exit 1
    
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
