name: Build and deploy ASP.Net Core app to Azure Web App - ToDoWebApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Ensure this version matches your project requirements

      - name: Build with dotnet
        run: dotnet build ToDoApi/ToDoApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ToDoApi/ToDoApi.csproj -c Release -o ${{github.workspace}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This permission is required for Azure login

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ${{github.workspace}}/myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D9CDC34EF91C4C709E3F5F4E6131CD14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_608BD21022E443AAADC216C3ACAF9726 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74FC7A3086834A8594FCA280ADE34287 }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ToDoWebApi'
          package: ${{github.workspace}}/myapp  # This should be the path to the folder containing the published application files
